const {Router} = require("express");
const blogController = require("../controllers/blogController");
const router = new Router();
router.get("/", blogController.getIndex);
router.get("/post/:id", blogController.getSinglePost);
router.get("/contact", blogController.getContactPage);
router.post("/contact", blogController.handlerContact);
router.get('/captcha.png', blogController.getCaptcha);
router.post("/search", blogController.handlerSearch);
module.exports = router;